FORMAT: 1A
HOST: http://webgis.nature.cz/aopkrest/lifecs/

# AOPK ČR - Life CS - Druhy a Biotopy

Rozhraní pro získávání informací o **druzích a biotopech na lokalitách life české středohoří**
 
## Lokality Life CS - seznam [/lokality/?f={f}]

+ Parameters
    + f (string, optional) - formát výstupu
        + Default: html
        + Members
            + pjson - formátovaný json
            + json
            + html
            + xml

### Přehled dotazů [GET]

+ Response 200 (application/json)
  + Attributes (array[Lokalita])
  + Attributes (array[Lokalita])

## Lokality Life CS - poslední změna [/zmeny/lokality/?f={f}]

+ Parameters
    + f (string, optional) - formát výstupu
        + Default: html
        + Members
            + pjson - formátovaný json
            + json
            + html
            + xml

### Přehled dotazů [GET]

+ Response 200 (application/json)
  + Attributes (Zmena)


## Číselníky [/ciselniky?f={f}]
+ Parameters
    + f (string, optional) - formát výstupu
        + Default: json
        + Members
            + json
            + pjson
            + html
            + xml

### Číselníky [GET]

+ Response 200 (application/json)



# Data Structures

##Lokalita
+ LokalitaId: 4 (number) - id lokality /IDX_OBJEKT/
+ Biotopy (array) - Výstupy viz zdroj dat v tabulce V_LF_BIOTOP - v popisu je uveden /SLOUPEC TABULKY/
    + (Biotop)
    + (Biotop)
+ Druhy (array) - Výstupy viz zdroj dat v tabulce V_LF_DRUH - v popisu je uveden /SLOUPEC TABULKY/
    + (Druh)
    + (Druh)


##Biotop
+ StanovisteKod: 91F0 (string) - Kód typu přírodního stanoviště /HABITAT/
+ StanovisteNazev: `Smíšené lužní lesy s dubem letním (Quercus robur) jilmem vazem (Ulmus laevis) a jilmem habrolistým (Ulmus minor) jasanem ztepilým (Fraxinus excelsior) nebo jasanem úzkolistým (Fraxinus angustifolia) podél velkých řek (Ulmenion minoris)` (string) - Název typu přírodního stanoviště /NAZEV_HABITAT/
+ StanovisteNazevEN: `Riparian mixed forest of Quercus robur, Ulmus laevis and Ulmus minor, Fraxinus excelsior or Fraxinus angustifolia along the great rivers (Ulmenion minoris)` (string) - Název typu přírodního stanoviště v angličtině /NAME_HABITAT/
+ Kod: L2.3 (string) - Kód biotopu /KOD/
+ Nazev: Tvrdé luhy nížinných řek (string) - Název Biotopu /BIOTOP/ *obsahuje formátování latinských názvů kurzívou <i></i>*
+ NazevEN: Tvrdé luhy nížinných řek (string) - Název Biotopu v angličtině  /BIOTOP/ * obsahuje formátování latinských názvů kurzívou <i></i>*
+ Rozloha (object)
    + RozlohaHodnota: 1164.5611 (number) - Rozloha biotopu - číselně - /ROZLOHA/
    + RozlohaJednotka: ha (string) - Rozloha biotopu - jednotka - /v tabulce není/
    + UIValue: 1 164.561 ha (string) - rozloha biotopu zformátovaná pro výstup - /v tabulce není/
+ RozlohaRelativni: 18.8 (number) - relativní rozloha biotopu /ROZLOHA_REL/
+ Kvalita: 2.12 (number) - Kvalita biotopu /KVALITA/


##Druh
+ DruhKat: Obojživelníci (string) - Kategorie /DRUHKAT/
+ DruhNazevLat: Bufo bufo (string) - Latinský název druhu /DRUHNAZEVLAT/
+ DruhNazevCz: ropucha obecná (string, optional) - Český název druhu /DRUHNAZEVCZ/
+ OchranaKat: Ohrožený (string) - Kategorie /OCHRANAKAT/
+ Smernice: null (string) - /SMERNICE/ 
+ CervenySeznam: null (string) - Červený seznam /CERVENYSEZNAM/
+ RokPoslZaz: 2015 (number) - rok posledního záznamu /POSLEDNI_ROK/
+ DruhKarta: `http://portal.nature.cz/publik_syst/nd_nalez-public.php?idTaxon=4` (string) - odkaz na kartu druhu - jako odkaz z Latinský název druhu  `http://portal.nature.cz/publik_syst/nd_nalez-public.php?`** \IDX_OBJEKT\ **

##CISDRUH



##CISBIOTOP



##Zmena
+ DateT: `2018-05-14` (string) - poslední změna v datech



 {
         "Ciselniky": {
          "Biotopy": [
           {
            "Popis": "Slaniska",
            "Kod": "T7",
            "HabitatName": "Inland salt meadows",
            "Habitat": "1340",
            "HabitatNazev": "Vnitrozemské slané louky"
           },{
            "Popis": "Jednoletá vegetace písčin",
            "Kod": "T5.1",
            "HabitatName": "Inland dunes with open Corynephorus and Agrostis grasslands",
            "Habitat": "2330",
            "HabitatNazev": "Otevřené trávníky kontinentálních dun s paličkovcem (Corynephorus) a psinečkem (Agrostis)"
        }],
          "Druhy": [
           {
            "Kat": "Obojživelníci",
            "CervenySeznam": "Ohrožený (EN)",
            "NazevCZ": "kuňka obecná",
            "NazevLAT": "Bombina bombina",
            "IdNdTaxon": 1,
            "Smernice": "HD II, HD IV",
            "Ochrana": "Silně ohrožený"
           },{
            "Kat": "Obojživelníci",
            "CervenySeznam": "Ohrožený (EN)",
            "NazevCZ": null,
            "NazevLAT": "Bombina sp.",
            "IdNdTaxon": 2,
            "Smernice": null,
            "Ochrana": null
           }]
         }
    }